#!/bin/bash

path=${1}
progname=${2}

cd $path

if [ -f Makefile ]; 
then 
	make
	if [[ $? -eq 0 ]]; 
	then
		COMPILE="PASS"
		valgrind --leak-check=full --error-exitcode=1 ./main
		if [[ $? -eq 0 ]]; 
		then
			MEMCHECK="PASS"
			valgrind --tool=helgrind --error-exitcode=1 ./main
			if [[ $? -eq 0 ]]; 
			then
				THREAD="PASS"
				echo "0"
			else 
				THREAD="FAIL"
				echo "1"
			fi
		else
			MEMCHECK="FAIL"
			valgrind --tool=helgrind --error-exitcode=1 ./main
			if [[ $? -eq 0 ]]; 
			then
				THREAD="PASS"
				echo "2"
			else
				THREAD="FAIL"
				echo "3"
			fi
	fi
	echo
	echo "Compilation	Memory leaks	Thread race"
	echo "  $COMPILE		   $MEMCHECK	  	    $THREAD"

	else

	echo
	echo "Compilation	Memory leaks	Thread race"
	echo "  FAIL		   FAIL	  	       FAIL"
	echo "7"
fi	
else
	echo "Makefile not found"
fi
